In [35]:
import numpy as np
import pandas as pd

In [40]:
df = pd.read_csv('Downloads/Countries.csv')
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [41]:
df.shape

(194, 64)

In [55]:
df[df['population'] == df['population'].max()]['country']

75    India
Name: country, dtype: object

In [56]:
df[df['population'] == df['population'].min()]['country']

179    Tuvalu
Name: country, dtype: object

In [62]:
df.sort_values('democracy_score', ascending = False , inplace = True)

In [63]:
df['country'].head()

127         Norway
74         Iceland
164         Sweden
122    New Zealand
46         Denmark
Name: country, dtype: object

In [66]:
df['continent'].tail()

154      Africa
161    Americas
160    Americas
159    Americas
97       Europe
Name: continent, dtype: object

In [67]:
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
127,Norway,Kingdom of Norway,Norwegian krone,Oslo,Northern Europe,Europe,Norwegian,62.000000,10.000000,9859.62,...,5457127,44.9704,891476,4565651,10.00,9.87,Full democracy,35.6,Erna Solberg,Prime Minister
74,Iceland,Republic of Iceland,Iceland krona,Reykjavík,Northern Europe,Europe,Icelander,65.000000,-18.000000,18720.00,...,381900,47.6190,22945,358955,5.32,9.58,Full democracy,32.1,Katrín Jakobsdóttir,Prime Minister
164,Sweden,Kingdom of Sweden,Swedish krona,Stockholm,Northern Europe,Europe,Swedish,62.000000,15.000000,30055.40,...,10486941,46.4183,1206837,9280104,9.41,9.39,Full democracy,35.6,Stefan Löfven,Prime Minister
122,New Zealand,New Zealand,New Zealand dollar,Wellington,Australia and New Zealand,Oceania,New Zealander,-41.000000,174.000000,101540.00,...,5124100,50.4202,672077,4452023,7.27,9.26,Full democracy,32.8,Jacinda Ardern,Prime Minister
46,Denmark,Kingdom of Denmark,Danish krone,Copenhagen,Northern Europe,Europe,Danish,56.000000,10.000000,26199.90,...,5903037,43.5754,686700,5216337,7.92,9.22,Full democracy,37.2,Mette Frederiksen,Prime Minister
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,Somalia,Somali Democratic Republic,Somali shilling,Mogadishu,Eastern Africa,Africa,Somali,10.000000,49.000000,441250.00,...,17597511,19.7080,9269665,8327846,1.37,0.00,Unknown,11.3,Hassan Ali Khayre,Prime Minister
161,St. Vincent and the Grenadines,St. Vincent and the Grenadines,East Caribbean dollar,Kingstown,Caribbean,Americas,Saint Vincentian,13.250000,-61.200000,70.00,...,103948,18.1818,47946,56002,0.00,0.00,Unknown,29.1,NaN,NaN
160,St. Lucia,St. Lucia,East Caribbean dollar,Castries,Caribbean,Americas,Saint Lucian,13.883333,-60.966667,99.40,...,179857,11.1111,145594,34263,0.00,0.00,Unknown,29.5,NaN,NaN
159,St. Kitts and Nevis,St. Kitts and Nevis,East Caribbean dollar,Basseterre,Caribbean,Americas,Kittian and Nevisian,17.333333,-62.750000,60.00,...,47657,31.2500,32888,14769,0.00,0.00,Unknown,30.4,NaN,NaN
97,Liechtenstein,Principality of Liechtenstein,Swiss franc,Vaduz,Western Europe,Europe,Liechtensteiner,47.266667,9.533333,53.20,...,39327,28.0000,33610,5717,3.82,0.00,Unknown,39.9,Hereditary Prince Alois,Regent

In [78]:
df[['country','population']]

                            country  population
127                          Norway     5457127
74                          Iceland      381900
164                          Sweden    10486941
122                     New Zealand     5124100
46                          Denmark     5903037
..                              ...         ...
154                         Somalia    17597511
161  St. Vincent and the Grenadines      103948
160                       St. Lucia      179857
159             St. Kitts and Nevis       47657
97                    Liechtenstein       39327

[194 rows x 2 columns]

In [79]:
df['country'].head(10)

127         Norway
74         Iceland
164         Sweden
122    New Zealand
46         Denmark
79         Ireland
30          Canada
59         Finland
8        Australia
165    Switzerland
Name: country, dtype: object

In [83]:
df[df['country'] == 'India']

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.0,77.0,1790450.0,...,1417173173,14.9446,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister

In [84]:
df[df['continent'] == 'Asis']

Empty DataFrame
Columns: [country, country_long, currency, capital_city, region, continent, demonym, latitude, longitude, agricultural_land, forest_area, land_area, rural_land, urban_land, central_government_debt_pct_gdp, expense_pct_gdp, gdp, inflation, self_employed_pct, tax_revenue_pct_gdp, unemployment_pct, vulnerable_employment_pct, electricity_access_pct, alternative_nuclear_energy_pct, electricty_production_coal_pct, electricty_production_hydroelectric_pct, electricty_production_gas_pct, electricty_production_nuclear_pct, electricty_production_oil_pct, electricty_production_renewable_pct, energy_imports_pct, fossil_energy_consumption_pct, renewable_energy_consumption_pct, co2_emissions, methane_emissions, nitrous_oxide_emissions, greenhouse_other_emissions, urban_population_under_5m, health_expenditure_pct_gdp, health_expenditure_capita, hospital_beds, hiv_incidence, suicide_rate, armed_forces, internally_displaced_persons, military_expenditure_pct_gdp, birth_rate, death_rate, fertility_rate, internet_pct, life_expectancy, net_migration, population_female, population_male, population, women_parliament_seats_pct, rural_population, urban_population, press, democracy_score, democracy_type, median_age, political_leader, title]
Index: []

[0 rows x 64 columns]

In [87]:
df[df['population'] == df['population'].max()]['country']

75    India
Name: country, dtype: object