In [2]:
#pandas series
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import numpy as np
import pandas as pd

In [5]:
labels = ['a' , 'b' , 'c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10 , 2:20 , 3:30}

In [6]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [11]:
pd.Series(arr , index = labels)

a    10
b    20
c    30
dtype: int64

In [13]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [31]:
data = {
    'name':  ['john' , 'anna' , 'peter' , 'linda'],
    'Age' : [28,34, 29 , 32],
    'City' : ['new york' , 'paris' , 'Berlin' , 'London'],
    'salary' : [65000 , 70000 , 62000 , 85000]
}
df = pd.DataFrame(data)
df

    name  Age      City  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    Berlin   62000
3  linda   32    London   85000

In [32]:
df['name']

0     john
1     anna
2    peter
3    linda
Name: name, dtype: object

In [33]:
pd.DataFrame(data['salary'])

       0
0  65000
1  70000
2  62000
3  85000

In [34]:
pd.DataFrame(data['Age'])

    0
0  28
1  34
2  29
3  32

In [35]:
df

    name  Age      City  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    Berlin   62000
3  linda   32    London   85000

In [39]:
data_list = [
    ['john' , 28, 'new york' , 65000],
    ['anna' , 34 , 'paris' , 70000],
    ['peter' , 29 , 'berlin' , 62000],
    ['linda' , 42 , 'london' , 85000]
]
df2 = pd.DataFrame(data_list)
headings = [ "name" , "age" , "city" , "salary"]
df2 = pd.DataFrame(data_list , columns = headings)
df2

    name  age      city  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000
3  linda   42    london   85000

df2

In [40]:
df2

    name  age      city  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000
3  linda   42    london   85000

In [42]:
pd.DataFrame(df2["name"])

    name
0   john
1   anna
2  peter
3  linda

In [44]:
df2["name"]

0     john
1     anna
2    peter
3    linda
Name: name, dtype: object

In [45]:
df2[["name","city"]]

    name      city
0   john  new york
1   anna     paris
2  peter    berlin
3  linda    london

In [60]:
df2

    name  age      city  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000
3  linda   42    london   85000

In [61]:
df2["designation"] = ["doctor", "enginner" , "lawyer" , "scientist"]
df2

    name  age      city  salary designation
0   john   28  new york   65000      doctor
1   anna   34     paris   70000    enginner
2  peter   29    berlin   62000      lawyer
3  linda   42    london   85000   scientist

In [62]:
df2.drop("designation" , axis = 1)

    name  age      city  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000
3  linda   42    london   85000

In [63]:
df2.drop("designation", axis = 1 , inplace = True)

In [64]:
df2.drop(0, axis = 0 )

    name  age    city  salary
1   anna   34   paris   70000
2  peter   29  berlin   62000
3  linda   42  london   85000

In [65]:
df2

    name  age      city  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000
3  linda   42    london   85000

In [66]:
df2.loc[1]

name       anna
age          34
city      paris
salary    70000
Name: 1, dtype: object

In [67]:
df2.loc[0]

name          john
age             28
city      new york
salary       65000
Name: 0, dtype: object

In [68]:
df2.loc[[0,3]]

    name  age      city  salary
0   john   28  new york   65000
3  linda   42    london   85000

In [69]:
df2

    name  age      city  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000
3  linda   42    london   85000

In [70]:
df2.loc[[0,1]][["city" , "salary"]]

       city  salary
0  new york   65000
1     paris   70000

In [71]:
df2.loc[[2,3]][["name" , "age"]]

    name  age
2  peter   29
3  linda   42

In [72]:
df2

    name  age      city  salary
0   john   28  new york   65000
1   anna   34     paris   70000
2  peter   29    berlin   62000
3  linda   42    london   85000

In [76]:
df2[df2["age"] > 30]

    name  age    city  salary
1   anna   34   paris   70000
3  linda   42  london   85000

In [78]:
df2[(df2["age"] > 30) & (df2["city"] == "paris")]

   name  age   city  salary
1  anna   34  paris   70000

In [86]:
data = {
     'a' : [1,2,np.nan , 4 ,5],
     'b' : [1,2,3,4,5],
     'c' : [1,2,3,np.nan,np.nan],
     'd' : [1, np.nan , np.nan , np.nan , 5]
}
df = pd.DataFrame(data)
df

     a  b    c    d
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [87]:
df.isna()

       a      b      c      d
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [88]:
df.isna().sum()

a    1
b    0
c    2
d    3
dtype: int64

In [89]:
df.isna().any()

a     True
b    False
c     True
d     True
dtype: bool

In [90]:
df.dropna()

     a  b    c    d
0  1.0  1  1.0  1.0

In [91]:
df.dropna(thresh = 3)

     a  b    c    d
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [92]:
df

     a  b    c    d
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [93]:
df.fillna(0)

     a  b    c    d
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [3]:
import numpy as np
import pandas as pd

employees = pd.DataFrame({
    'employee id' : [ 1,2,3,4,5],
    'name' : ['john' , 'anna' , 'peter' , 'linda' , 'bob'],
    'department' : ['hr' , 'it' , 'finance' , 'it' , 'hr']
})

salaries = pd.DataFrame({
    'employee id' : [1,2,3,6,7],
    'salary' : [60000,80000,65000,70000,90000],
    'bonus' : [5000,10000,7000,8000,12000]
})

employees

In [4]:
salaries

   employee id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [5]:
employees

   employee id   name department
0            1   john         hr
1            2   anna         it
2            3  peter    finance
3            4  linda         it
4            5    bob         hr

In [6]:
pd.merge(employees , salaries)

   employee id   name department  salary  bonus
0            1   john         hr   60000   5000
1            2   anna         it   80000  10000
2            3  peter    finance   65000   7000

In [8]:
pd.merge(employees , salaries , on = 'employee id' , how = 'inner')

   employee id   name department  salary  bonus
0            1   john         hr   60000   5000
1            2   anna         it   80000  10000
2            3  peter    finance   65000   7000

In [9]:
pd.merge(employees , salaries , on = 'employee id' , how = 'outer')

   employee id   name department   salary    bonus
0            1   john         hr  60000.0   5000.0
1            2   anna         it  80000.0  10000.0
2            3  peter    finance  65000.0   7000.0
3            4  linda         it      NaN      NaN
4            5    bob         hr      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [10]:
pd.merge(employees , salaries , on = 'employee id' , how = 'left')

   employee id   name department   salary    bonus
0            1   john         hr  60000.0   5000.0
1            2   anna         it  80000.0  10000.0
2            3  peter    finance  65000.0   7000.0
3            4  linda         it      NaN      NaN
4            5    bob         hr      NaN      NaN

In [11]:
pd.merge(employees , salaries , on = 'employee id' , how = 'right')

   employee id   name department  salary  bonus
0            1   john         hr   60000   5000
1            2   anna         it   80000  10000
2            3  peter    finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [12]:
pd.concat([employees , salaries])

   employee id   name department   salary    bonus
0            1   john         hr      NaN      NaN
1            2   anna         it      NaN      NaN
2            3  peter    finance      NaN      NaN
3            4  linda         it      NaN      NaN
4            5    bob         hr      NaN      NaN
0            1    NaN        NaN  60000.0   5000.0
1            2    NaN        NaN  80000.0  10000.0
2            3    NaN        NaN  65000.0   7000.0
3            6    NaN        NaN  70000.0   8000.0
4            7    NaN        NaN  90000.0  12000.0

In [16]:
pd.concat([employees , salaries], axis = 1)

   employee id   name department  employee id  salary  bonus
0            1   john         hr            1   60000   5000
1            2   anna         it            2   80000  10000
2            3  peter    finance            3   65000   7000
3            4  linda         it            6   70000   8000
4            5    bob         hr            7   90000  12000

In [31]:
df1 = pd.DataFrame({
    'name' : ['alice' , 'bob' , 'charlie']
}, index = [ 1,2,3])

df2 = pd.DataFrame({
    'score' : [85 , 90 , 75]
}, index = [1,2,4])

df1

In [32]:
df2

   score
1     85
2     90
4     75

In [33]:
df1

      name
1    alice
2      bob
3  charlie

In [34]:
df1.join(df2)

      name  score
1    alice   85.0
2      bob   90.0
3  charlie    NaN

In [35]:
df1.join(df2 , how = 'outer')

      name  score
1    alice   85.0
2      bob   90.0
3  charlie    NaN
4      NaN   75.0

In [36]:
df1

      name
1    alice
2      bob
3  charlie

In [37]:
df2

   score
1     85
2     90
4     75

In [39]:
data = {
'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
'Date': pd.date_range('2023-01-01', periods=8)
}

df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [43]:
cat = df.groupby('Category')
cat
for i , v in cat:
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [45]:
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [48]:
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [49]:
cat = df.groupby(['Store' , 'Category'])['Sales'].sum()
cat

Store  Category
S1     A           220
       B           500
S2     A           350
       B           430
Name: Sales, dtype: int64

In [50]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [51]:
df['Sales'].mean()

np.float64(187.5)

In [52]:
df['Quantity'].mean()

np.float64(15.375)

In [53]:
df['Sales'].median()

190.0

In [54]:
df['Sales'].std()

66.06274074155351

In [56]:
df['Sales'].var()

4364.285714285715

In [57]:
df['Sales'].count()

np.int64(8)

In [58]:
df['Sales'].max()

300

In [59]:
df['Sales'].min()

100

In [61]:
df['Sales'].agg(['mean' , 'std' , 'median' , 'min' , 'max' , 'count','sum'])

mean       187.500000
std         66.062741
median     190.000000
min        100.000000
max        300.000000
count        8.000000
sum       1500.000000
Name: Sales, dtype: float64

In [62]:
data = {
'Date': pd.date_range('2023-01-01', periods=20),
'Product': ['A', 'B', 'C', 'D'] * 5,
'Region': ['East', 'West', 'North', 'South',
'East', 'West', 'North', 'South',
'East', 'West', 'North', 'South',
'East', 'West', 'North', 'South',
'East', 'West', 'North', 'South'],
'Sales': np.random.randint(100, 1000, 20),
'Units': np.random.randint(10, 100, 20),
'Rep': ['John', 'Mary', 'Bob', 'Alice',
'John', 'Mary', 'Bob', 'Alice',
'John', 'Mary', 'Bob', 'Alice',
'John', 'Mary', 'Bob', 'Alice',
'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    769     55   John  January      Q1
1  2023-01-02       B   West    237     74   Mary  January      Q1
2  2023-01-03       C  North    409     93    Bob  January      Q1
3  2023-01-04       D  South    204     39  Alice  January      Q1
4  2023-01-05       A   East    789     84   John  January      Q1
5  2023-01-06       B   West    314     11   Mary  January      Q1
6  2023-01-07       C  North    543     78    Bob  January      Q1
7  2023-01-08       D  South    949     97  Alice  January      Q1
8  2023-01-09       A   East    297     40   John  January      Q1
9  2023-01-10       B   West    951     37   Mary  January      Q1
10 2023-01-11       C  North    601     85    Bob  January      Q1
11 2023-01-12       D  South    409     86  Alice  January      Q1
12 2023-01-13       A   East    431     33   John  January      Q1
13 2023-01-14       B   West    450     18   Mary  January      Q1
14 2023-01-15       C  North    186     75    Bob  January      Q1
15 2023-01-16       D  South    871     41  Alice  January      Q1
16 2023-01-17       A   East    803     31   John  January      Q1
17 2023-01-18       B   West    535     89   Mary  January      Q1
18 2023-01-19       C  North    168     39    Bob  January      Q1
19 2023-01-20       D  South    759     73  Alice  January      Q1

In [64]:
pd.pivot_table(df , values = ['Units','Sales'] , index = 'Product' , columns = 'Region' , aggfunc = 'mean')

         Sales                      Units
Region    East  North  South   West  East North South  West
Product
A        617.8    NaN    NaN    NaN  48.6   NaN   NaN   NaN
B          NaN    NaN    NaN  497.4   NaN   NaN   NaN  45.8
C          NaN  381.4    NaN    NaN   NaN  74.0   NaN   NaN
D          NaN    NaN  638.4    NaN   NaN   NaN  67.2   NaN

In [65]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    769     55   John  January      Q1
1  2023-01-02       B   West    237     74   Mary  January      Q1
2  2023-01-03       C  North    409     93    Bob  January      Q1
3  2023-01-04       D  South    204     39  Alice  January      Q1
4  2023-01-05       A   East    789     84   John  January      Q1
5  2023-01-06       B   West    314     11   Mary  January      Q1
6  2023-01-07       C  North    543     78    Bob  January      Q1
7  2023-01-08       D  South    949     97  Alice  January      Q1
8  2023-01-09       A   East    297     40   John  January      Q1
9  2023-01-10       B   West    951     37   Mary  January      Q1
10 2023-01-11       C  North    601     85    Bob  January      Q1
11 2023-01-12       D  South    409     86  Alice  January      Q1
12 2023-01-13       A   East    431     33   John  January      Q1
13 2023-01-14       B   West    450     18   Mary  January      Q1
14 2023-01-15       C  North    186     75    Bob  January      Q1
15 2023-01-16       D  South    871     41  Alice  January      Q1
16 2023-01-17       A   East    803     31   John  January      Q1
17 2023-01-18       B   West    535     89   Mary  January      Q1
18 2023-01-19       C  North    168     39    Bob  January      Q1
19 2023-01-20       D  South    759     73  Alice  January      Q1

In [66]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [67]:
df1 = pd.DataFrame({
'A': [1, 2, 3, 4, 5],
'B': [10, 20, 30, 40, 50],
'C': [100, 200, 300, 400, 500]
})

df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [68]:
df1.shape

(5, 3)

In [69]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [70]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [71]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [72]:
def square(x):
    return x**2

In [73]:
df1['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [76]:
df1['D'] = df1['B'].apply(square)
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500